# Generated by Django 5.0.3 on 2024-03-30 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='articles/images/'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='article.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(blank=True, null=True, to='article.category'),
        ),
    ]
