# Generated by Django 5.0.3 on 2024-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/images/'),
        ),
    ]
